---
# tasks file for opennebula

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: opennebula

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: opennebula

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: opennebula
